-- V6: PAR formula fields + PO suggestion table (HIGH-02)

-- Add avg_daily_usage and lead_time_days to inventory_items
ALTER TABLE inventory_items
    ADD COLUMN IF NOT EXISTS avg_daily_usage  NUMERIC(12,4),
    ADD COLUMN IF NOT EXISTS lead_time_days   INTEGER;

-- PO suggestions generated by PAR formula scan
CREATE TABLE IF NOT EXISTS po_suggestions (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id           UUID        NOT NULL,
    inventory_item_id   UUID        NOT NULL REFERENCES inventory_items(id),
    supplier_id         UUID,
    suggested_quantity  NUMERIC(12,4) NOT NULL,
    current_stock       NUMERIC(12,4) NOT NULL,
    par_level           NUMERIC(12,4) NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','approved','rejected','converted')),
    approved_by         UUID,
    converted_po_id     UUID,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_po_suggestions_tenant_status
    ON po_suggestions (tenant_id, status, created_at DESC);

ALTER TABLE po_suggestions ENABLE ROW LEVEL SECURITY;
CREATE POLICY IF NOT EXISTS tenant_isolation ON po_suggestions
    USING (tenant_id = current_setting('app.current_tenant_id', TRUE)::UUID);
