/**
 * Global test setup for the API Gateway.
 *
 * Provides all required env vars so config/index.ts passes Zod validation.
 * JWT_PUBLIC_KEY is set to the RSA test public key generated by TestKeyHelper.
 */
Object.assign(process.env, {
  NODE_ENV:                    'test',
  AUTH_SERVICE_URL:            'http://auth-service:8081',
  INVENTORY_SERVICE_URL:       'http://inventory-service:8082',
  FINANCE_SERVICE_URL:         'http://finance-service:8083',
  STAFF_SERVICE_URL:           'http://staff-service:8088',
  AI_SERVICE_URL:              'http://ai-service:8084',
  FILE_SERVICE_URL:            'http://file-service:8085',
  NOTIFICATION_SERVICE_URL:    'http://notification-service:8086',
  REPORT_SERVICE_URL:          'http://report-service:8087',
  JWT_PUBLIC_KEY:              'PLACEHOLDER', // overridden per-test via vi.mock
  REDIS_URL:                   'redis://localhost:6379',
  INTERNAL_SERVICE_SECRET:     'test-internal-secret',
});
